---
- hosts: all
  roles:
     #- jeqo.nginx
     #- { role: makeittotop.apache2,  become: yes }
     #- stevenharradine.apache2
     #- { role: lciolecki.virtualenvwrapper,  become: yes }
     - { role: angstwad.docker_ubuntu,  become: yes }
     - { role: makeittotop.dockerimage, become: yes }
